name: Build Executable
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller==6.2.0

      - name: Build EXE
        shell: cmd  # 关键修复：使用CMD代替PowerShell
        run: |
          pyinstaller --onefile --windowed --icon=src/icon.ico --add-data "src/icon.ico;." src/main.py
          dir dist\  # 简化的目录查看命令

      - name: Verify EXE
        run: |
          if not exist dist\main.exe (
            echo "::error::EXE file not generated!"
            exit 1
          )
          echo "File size:"
          dir dist\main.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: jianying-exporter
          path: dist/main.exe
          retention-days: 5
